server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://192.168.66.41:3406/test?useUnicode=true&amp;characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 获取连接超时时间（默认30秒，最小不能小于250毫秒）
      connection-timeout: 30000
      # 池中连接最长空闲时间（默认10分钟，且大于10秒）,当minimum-idle小于maximum-pool-size时，且空闲时间超过idle-timeout时，连接将从池中移除
      idle-timeout: 600000
      # 池中连接最长生命周期（默认30分钟）
      max-lifetime: 1800000
      # 最小空闲连接数
      minimum-idle: 5
      # 最大连接数（默认10）
      maximum-pool-size: 10
      # 验证连接有效性的超时时间(默认5秒，最小不能小于250毫秒)
      validation-timeout: 5000
      connection-test-query: SELECT 1
      # 获取连接的时间 + 使用连接的时间 + 还回连接的时间，超出了leak-detection-threshold毫秒，就抛出检测到连接泄露的异常
      leak-detection-threshold: 5000

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
      jdbc:
        batch_size: 10
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect